dist: trusty
language: java
jdk:
  - oraclejdk11
services:
  - docker

script:
  - set -e
  - ./gradlew jar
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t catbot:latest .
  - docker tag catbot:latest $DOCKER_USERNAME/catbot:latest
  - docker push $DOCKER_USERNAME/catbot:latest
