dist: trusty
language: java
jdk:
  - openjdk17
services:
  - docker

jobs:  
  include:
    - stage: "Tests"
      name: "Unit Tests"
      script: 
       - ./gradlew test
       - set -e
    - stage: "Docker image"
      if: branch = master AND type = push
      name: "Build & push docker image"
      script:
       - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
       - docker build -t catbot:latest .
       - docker tag catbot:latest $DOCKER_USERNAME/catbot:latest
       - docker push $DOCKER_USERNAME/catbot:latest
