name: Build image

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run tests
        run: ./gradlew test
      - name: Build jar
        run: ./gradlew jar
      - name: Docker Login
        if: github.ref == 'refs/heads/master'
        uses: docker/login-action@v3.3.0
        with:
          # Server address of Docker registry. If not set then will default to Docker Hub
          registry: ghcr.io
          # Username used to log against the Docker registry
          username: ${{ github.actor }}
          # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        if: github.ref == 'refs/heads/master'
        run: docker build -t ghcr.io/romangr/catbot:latest .
      - name: Publish the Docker image
        if: github.ref == 'refs/heads/master'
        run: docker push ghcr.io/romangr/catbot:latest
